### ISSUE TITLE
CUDA support Linux/Windows

### ISSUE THREAD

**Issue by moiseshorta** [acids-ircam/nn_tilde#10]
Hi, 

I just read on twitter (https://twitter.com/hexorcismos/status/1526857851561467905?s=20&t=kUAJZFaNKl4nXZDV2JSNfg) that it is possible to have nn~ take advantage of CUDA enabled machines.

What would be the procedure for this? Just download the CUDA enabled LibTorch instead of CPU, and point to that folder when compiling?

Looking forward to try it out!

Best,
M

**Comment by CarloCattano** [comment]
yes , and on windows also cuDNN.
Had to fix some enviroment variables and manually install cuDNN as explained here.
No clue on linux yet , but will follow here to get updates about it , even tho is also covered in the guide ( Linux section ), so I assume its doable:
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html

**Comment by timmb** [comment]
@CarloCattano On Windows I can build OK but when I instantiate the object I get the error "The procedure entry point ?warp_size@cuda@at@@YAHXZ could not be located in the dynamic link library ...\gpunn_tilde\nn~.mxe64".

I've added all the Torch and CUDA dlls to the path (including torch_cuda.dll which has the required entry point). Did you get hit this?
