### ISSUE TITLE
Building from source only produces max externals

### ISSUE THREAD

**Issue by weyesnob** [acids-ircam/nn_tilde#12]
I have built nn_tilde from source on Windows 11, but the src/externals folder only contains .mxe64 files which are incompatible with Pd. Is there any way to build the Pd externals from source as of yet?

**Comment by delmenhorst** [comment]
yes it its possible! you have to include the pure data source files to compile it.

**Comment by weyesnob** [comment]
Thanks for the response, @delmenhorst. I just tried including the pure data source by supplying cmake with an argument -DPUREDATA_INCLUDE_DIR that points to the src folder of the Pd repository, but I'm getting a fatal error when building. Could you please specify what you mean when you write "include the pure data source files"? Thanks a lot.

Also, in the CMakeLists.txt file in the src directory of this repo, it performs this check before creating the directory frontend/puredata/nn_tilde:
`if ((APPLE AND NOT ("${PUREDATA_INCLUDE_DIR}" STREQUAL "")) OR (UNIX AND NOT APPLE))` 
This suggests to me that building the Pd external may be only possible on Apple and Linux. Have you had success building it on Windows before?

**Comment by caillonantoine** [comment]
Unfortunately I don't have a windows machine to test with, so I can't really help here... @robclouth do you want to give it a shot ?

**Comment by robclouth** [comment]
Sorry I only tested with MaxMSP for the windows build as I'm not familiar with building Pd externals. It may be that the cmakelists needs to have some minor tweaks.

**Comment by RyanMillett** [comment]
Are there pre-built binaries for Pd (on Mac)?  I see the Max ones but not Pd.

**Comment by ayk-caglayan** [comment]
I'm also looking for pre-built Pd binary for mac os. I hope someone who succeds to build it share with us

**Comment by danomatika** [comment]
I also wanted to try this managed to get it to build with the following caveats:

* you have to provide the path to the src file where the headers live within the Pd app bundle, ie. `/Applications/Pd-0.52-2.app/Contents/Resources/src`
* cmake can't find libtorch unless you provide the path as an Torch_DIR env export
* the official libtorch builds are currently x86_64 only, so the arch needs to be overridden on arm64 machines (M1, etc)
* on M1 machines, Pd needs to be run through Rosetta to be able to load the external
* there is no documentation on how to use the external or help files I can see, so once built it's not very useful (yet)
* the built object has only a single input and no output(s)?

## Build Script

In any case, I wrapped these steps up into a build script if anyone wants to try for themselves. You will need Xcode or the Commandline Tools installed as well as cmake.

https://gist.github.com/danomatika/550d382166f33398cea4b381a77a6ef6

## Suggestion to Devs

Check out [pd-lib-builder](https://github.com/pure-data/pd-lib-builder) which automates most of the build process for Pd externals. For an example of using it with C++ objects, see https://github.com/zkmkarlsruhe/ZirkoniumSpatializationServer/tree/main/externals/hoa

**Comment by danomatika** [comment]
Howdy again, I decided to try building with libtorch installed via Homebrew which is pre-built for arm64 on my machine. This works fine with the caveat that the build external will most likely not be portable to other systems since it relies on the libtorch dylib.

The new script is here: [build-nn_tilde-macos-brew.sh](https://gist.github.com/danomatika/15d7b7f87392cf7883b745bedba5892d#file-build-nn_tilde-macos-brew-sh)

**Comment by ttoommmmiiee** [comment]
Hi @danomatika did you make any progress on this? I built the Puredata external using a slightly modified version of your script. 

However, the resulting external doesn't work. When I first loaded the [nn~] in Pd, it did come up with the credit/version message in the console. But, as you described, it only has one inlet and no outlets. Trying to load models results in 'error during loading'. 

Here's my script: 
[build-nn_tilde-macos-brew.sh](https://github.com/ttoommmmiiee/nn_tilde/blob/9d90e52a0cb64418b0daef80d11c8617eb20ff36/install/build-nn_tilde-macos-brew.sh)

I built this on: 
Mac M1 Monterey 12.3.1 
Puredata  Pd 0.52.2
pytorch 1.13.1

**Comment by caillonantoine** [comment]
Can you take a screenshot of your patch ?

**Comment by ttoommmmiiee** [comment]
<img width="717" alt="Screenshot 2023-01-24 at 12 54 28" src="https://user-images.githubusercontent.com/64283052/214297896-f1c48854-7113-487d-aff5-96da4914710f.png">

**Comment by caillonantoine** [comment]
You should use the absolute path of the pretrained model when using nn~ for PureData. This bug has apparently been fixed in #27, but I didn't have the time to review it.

**Comment by ttoommmmiiee** [comment]
Success! 
<img width="582" alt="Screenshot 2023-01-24 at 13 14 00" src="https://user-images.githubusercontent.com/64283052/214303887-59a5c715-6b03-471f-87c3-e6c262424ce2.png">

**Comment by danomatika** [comment]
I did not look any further. Other projects came up.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
