### ISSUE TITLE
[MacOS] nn~: could not load due to incorrect architecture

### ISSUE THREAD

**Issue by victorburton** [acids-ircam/nn_tilde#14]
Hi! 

Cannot load the prebuilt x86 version of nn~. Console output; _nn~: could not load due to incorrect architecture_

Intel MacBook Pro 2018 2,7 Ghz Intel i7 quad core. Currently running OS version 12.1. Using latest Max version. 

Any help would be greatly appreciated!

**Comment by caillonantoine** [comment]
You are using the wrong binary, i.e arm64. If you are using an intel macbook, you should use the x86 build available [here](https://github.com/acids-ircam/nn_tilde/releases/download/v1.3.1/nn_max_msp_macOS_x86_64.tar.gz)

**Comment by victorburton** [comment]
Hello,

Thank you for the follow-up. I was using x86. I tried installing it again via the link you provided; unfortunately still the same result. 

I may have [wrongfully] installed arm64 a few weeks ago; perhaps the now x86 persistent issue is cache-related?
