### ISSUE TITLE
If the decoder generates blocks of 65536 samples, do you discard the rest when filling the output buffer?

### ISSUE THREAD

**Issue by robclouth** [acids-ircam/nn_tilde#15]
Say if the output buffer is 512 long, only the first 512 samples of the generated block are used?

**Comment by caillonantoine** [comment]
If the output buffer is 512, the model will either generate a block of 512 audio samples, or wait for several cycles to fill the buffer then process the full sequence (e.g 4096 samples). Those 4096 samples are then filling the output buffer 512 per 512
