### ISSUE TITLE
pd version just load models with global path

### ISSUE THREAD

**Issue by delmenhorst** [acids-ircam/nn_tilde#19]
Hey, 

There is a little thing which a bit is annoying. the object just can load the models with the absolute path. Everything else fails. (declare paths etc....).Unfortunately this is not really handy. 

The PD-Mail Group gave a hint for some fix:

```
// SEARCH FOR FILE
 if (!sys_isabsolutepath(x->m_path->s_name)) {
   char dirname[MAXPDSTRING], *dummy;
   auto fd = open_via_path("", x->m_path->s_name, "", dirname, &dummy,
                           MAXPDSTRING, 1);
   std::string found_path;
   found_path += dirname;
   found_path += "/";
   found_path += x->m_path->s_name;
   x->m_path = gensym(found_path.c_str());
 } 
```

_"open_via_path() only considers the global search paths. You (almost) always want to use canvas_open() instead, which also uses the canvas environment (i.e. patch relative paths + paths added with [declare]).

Note that you would need a reference to the containing canvas. This can be done by calling canvas_getcurrent() in the constructor and storing the resulting t_canvas* in the object."_

I tried to implement the fix, but it doesn't work well. May be someone could help?

**Comment by delmenhorst** [comment]
Actually I am facing a kind of similar problem with max. 
When I am running the native nn~  version on my M1 Machine it doesn't load the model.
Running with Rosetta the x86 version doesn't make problems.

Is this an ARM64 problem? Does someone have the same bug?

**Comment by caillonantoine** [comment]
Regarding the max version, you should use the arm64 binaries !

**Comment by delmenhorst** [comment]
I solved the max thing. €&)(€…..&$ // nn~ // RAVEhttps://youtu.be/YqCLOAvfDms:)Am 13.01.2023 um 15:22 schrieb Antoine Caillon ***@***.***>:﻿
Regarding the max version, you should use the arm64 binaries !

**Comment by caillonantoine** [comment]
Nice work !
