### ISSUE TITLE
`nn~` causes max to crash after some time while running RAVE models on windows

### ISSUE THREAD

**Issue by nshaheed** [acids-ircam/nn_tilde#24]
OS: Win 10 & 11
CPU: intel i9-11900k (desktop) & intel i7-12700h (laptop)

When running a rave model on nn~ on windows, after some time max completely crashes. This happens fairly randomly and sometimes and error message pops up and sometimes it doesn't.

Things I've tried:
- running max from the command line, there's no stack trace or anything else printed out at the time of crash
- compiling the max externals myself and using the prebuilt binaries linked in #18. It crashes with both.

Thanks for the work on this! having a lot of fun with it

**Comment by nshaheed** [comment]
This is the error message I sometimes get:

![image](https://user-images.githubusercontent.com/6963603/191127269-40f35377-5023-47da-8f65-1b441d31391b.png)

**Comment by caillonantoine** [comment]
Hi, can you try and monitor your RAM usage and see if it is increasing during usage ? It might be a memory leak from the windows version of nn~ !

**Comment by nshaheed** [comment]
hmm it is indeed a memory leak. Looking at the heap snapshot it seems to be occurring in Backend::perform

**Comment by nshaheed** [comment]
More specifically, there is an increasing number of torch::jit::Nodes as well as other things relating to the torch models so it seems like the memory leak is occurring due to torch. Whether that's a leak within your code or the windows torch implementation I'm not sure yet. Visual studio keeps crashing when I try to do heap analysis so I haven't been able to dive much deeper than that.

**Comment by nshaheed** [comment]
Okay I've done some more investigating at it looks like the memory leak is happening when calling the model methods at https://github.com/acids-ircam/nn_tilde/blob/master/src/backend/backend.cpp#L55 

Here's the full allocation stack that I'm looking at

![image](https://user-images.githubusercontent.com/6963603/191614891-c020425f-64ba-45a7-b432-b4adb9df741c.png)


I'm not sure it's a memory leak per-se since m_model is persisting, but I think that some part of the model is growing on the backend with each call to perform()

**Comment by nshaheed** [comment]
I commented out [these lines](https://github.com/acids-ircam/nn_tilde/blob/master/src/backend/backend.cpp#L54-L61), and replace them with a tensor full of zeroes and that stopped the memory usage, so the leak is definitely coming from there
