### ISSUE TITLE
Choppy audio on Mac

### ISSUE THREAD

**Issue by JeremyKeenan** [acids-ircam/nn_tilde#26]
Audio plays back well with the 'wheel' model, but with the 'vintage' and 'percussion' model the audio becomes choppy - sounds slightly like CPU maxing out, or like a square wave tremelo, but CPU reading on max is at 2%.

Same results with forward, encoder/decoder and priors.

I am on an older Mac Air, 2015 OS 10.13.6, 8GB RAM.

**Comment by JeremyKeenan** [comment]
On second look, it does appear to be CPU spiking that the meter only picks up occasionally.

I'm on a 2.2 Ghz intel i7

**Comment by JeremyKeenan** [comment]
OK - I tried the 'vintage' model on a better CPU and updated OS.

The model plays OK with the 'forward' object, but when using the 'encode/decode' objects, I get the CPU spikes - goes rapidly between 1% and 100% CPU usage.

IMac Pro 2017
2.5GHz 14-Core Intel Xeon W
64 GB Ram
OS 11.4

**Comment by caillonantoine** [comment]
Vintage is pretty big, but you can lighten the processor load by increasing the buffer size (see the help patch).

**Comment by jeremy-keenan** [comment]
Thank you, that works - I can also confirm that it runs smoothly on both and mac and PC with higher RAM and CPU specs.
