### ISSUE TITLE
pre-built arm64 nn~ binary -> "incorrect archiecture" on m1

### ISSUE THREAD

**Issue by epleaner** [acids-ircam/nn_tilde#28]
Hey, I I download the pre-built binary under Releases ("nn_max_msp_macOS_arm64.tar.gz") and put the external into my Packages directory. When I create a nn~ object in Max, the console reports "nn~: could not load due to incorrect architecture". 

I'm on an M1.

**Comment by epleaner** [comment]
Same issue when building from source.

**Comment by caillonantoine** [comment]
What is your Max version ? Are you it is being launched without Rosetta ?

**Comment by Abbienew** [comment]
I faced the same issue
