### ISSUE TITLE
is there a nn~ version that can work in Rosetta?

### ISSUE THREAD

**Issue by BKopps** [acids-ircam/nn_tilde#33]
Hey guys

I want to create a soundscape using some devices that require Ableton to run in Rosetta since I have a Mac M1 Silicon.

I also want to use some MaxForLive devices that I've created using nn~ but these devices do not work in Rosetta. 

Is there any version of nn~ that would allow me to work in Rosetta?

Thanks!

**Comment by caillonantoine** [comment]
`nn~` indeed works with Rosetta, be sure to grab the correct version in the releases (i.e. macos x64)
