### ISSUE TITLE
Loading error when calling nn~ object

### ISSUE THREAD

**Issue by mirashindento** [acids-ircam/nn_tilde#38]
After following the compilation steps on Mac (intel) I got the following error when trying to load nn~ object:

` 2023-01-29 19:34:26.465 Max[19594:130193] Error loading /Users/xxxxxx/Documents/Max 8/Packages/nn_tilde/externals/nn~.mxo/Contents/MacOS/nn~:  dlopen(/Users/xxxxxx/Documents/Max 8/Packages/nn_tilde/externals/nn~.mxo/Contents/MacOS/nn~, 262): Library not loaded: @loader_path/../.dylibs/libiomp5.dylib
`

I tried to install libiomp with 
`brew install libiomp`
it seemed to have been installed properly but I still got the same error... 
Any help would be appreciated.

**Comment by caillonantoine** [comment]
Make sure to follow the updated installation instructions. Closing the issue for now, feel free to re-open if the issue persists !
