### ISSUE TITLE
where should I put some pretrained model to call nn~ in maxMSP?

### ISSUE THREAD

**Issue by gyuchulm** [acids-ircam/nn_tilde#39]
I've installed nn~ and I've searched the location to put some pre-trained model
where is the location to call a pre-trained model in maxMsp?

**Comment by RVirmoors** [comment]
your model (as a .ts file) should sit next to the .maxpat where you're using nn~

**Comment by caillonantoine** [comment]
You can also create a folder containing every `.ts` file and adding it to the max file path !
