### ISSUE TITLE
Feature Request: Usage instructions?

### ISSUE THREAD

**Issue by drscotthawley** [acids-ircam/nn_tilde#42]
Hey! Really looking forward to trying this out. Thanks for the build instructions. I have the pre-built binaries and/or I've also built my own. 

I have Max. I have PureData. I have Max for Live., ... uh...now what?

Are there any instructions for how to get this going?  

## In PureData:
There doesn't seem to be any help -- the help is just a picture of "nn~":
<img width="412" alt="Screen Shot 2023-02-24 at 7 36 01 PM" src="https://user-images.githubusercontent.com/13925685/221328932-9ac0f53e-fe17-4a66-b4e9-a6158a09845c.png">
The nn~ patch only seems to have one input and no outputs, so I'm not sure how to connect it to the DAC. 

## In Max:
I've watched [the demo video](https://www.youtube.com/watch?v=dMZs04TzxUI) but it seems to use a source patch called "Chromaphone" which... I can't find in Max. 
If I drag the nn~.mxo file in to Max, I get a patch showing the full path of where I dragged it from.  If I edit that to read "nn~ wheel foward" as is done in the video, then the Max console says "File not found":  
<img width="1148" alt="Screen Shot 2023-02-24 at 7 40 04 PM" src="https://user-images.githubusercontent.com/13925685/221329119-74f185d5-a52f-483f-870b-b07a6e2ba7f0.png">

If someone were to provide some Usage Instructions, or a link to a tutorial video, or a template file, that would be awesome!

**Comment by drscotthawley** [comment]
BTW I was able to open a mic and run the darbouka model! My voice now becomes drums (after a 1 second delay) :-) 

<img width="353" alt="Screen Shot 2023-02-24 at 8 35 09 PM" src="https://user-images.githubusercontent.com/13925685/221331885-6dd0872a-8092-4611-9e26-2edc5b00a6fa.png">

**Comment by caillonantoine** [comment]
We have added some documentation on the README, and additional videos are on the way !
