### ISSUE TITLE
Windows build error "Imported target "torch" includes non-existent path"

### ISSUE THREAD

**Issue by jeremy-keenan** [acids-ircam/nn_tilde#46]
I get this error when building for Windows 10

CMake Error in backend/CMakeLists.txt:
  Imported target "torch" includes non-existent path

    "C:\Program Files\NVIDIA Corporation\NvToolsExt\/include"

I have the latest CUDA installed and pointed cmake towards the libtorch build I downloaded and put in my users directory.

Any clues?

**Comment by jeremy-keenan** [comment]
Managed to get to build stage my installing CUDA 11.7

These errors then happen during build:

C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(88,7): error C3872: '0xa0': this character is
not allowed in an identifier [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(88,7): error C2065: 'Â ': undeclared identifie
r [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(88,33): error C2059: syntax error: ';' [C:\Use
rs\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(90,5): error C2059: syntax error: 'else' [C:\U
sers\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(90,1): error C2143: syntax error: missing ';'
before '{' [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(90,1): error C2447: '{': missing function head
er (old-style formal list?) [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(94,5): error C2059: syntax error: 'else' [C:\U
sers\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(94,1): error C2143: syntax error: missing ';'
before '{' [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(94,1): error C2447: '{': missing function head
er (old-style formal list?) [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(107,5): error C2059: syntax error: 'else' [C:\
Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(107,1): error C2143: syntax error: missing ';'
 before '{' [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(107,1): error C2447: '{': missing function hea
der (old-style formal list?) [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(127,5): error C2059: syntax error: 'else' [C:\
Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(127,1): error C2143: syntax error: missing ';'
 before '{' [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(127,1): error C2447: '{': missing function hea
der (old-style formal list?) [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(130,3): error C2059: syntax error: 'return' [C
:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(130,1): error C2143: syntax error: missing ';'
 before '{' [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(130,1): error C2447: '{': missing function hea
der (old-style formal list?) [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(131,1): error C2059: syntax error: '}' [C:\Use
rs\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]
C:\Users\jeremykeenan\nn_tilde\src\frontend\maxmsp\nn_tilde\nn_tilde.cpp(131,1): error C2143: syntax error: missing ';'
 before '}' [C:\Users\jeremykeenan\nn_tilde\build\frontend\maxmsp\nn_tilde\nn_tilde.vcxproj]

**Comment by jeremy-keenan** [comment]
OK, I was able to fix the above problem and build successfully. 

There was an errant invisible character in the main .cpp file  - deleting it  worked.

However, now I have this error in Max:

_Error 126 loading external nn~_

I have copied the libtorch dll folder into the Max application directory, and I have pointed the Max file preferences towards that folder.

Looking into it, it looks more like a compilation problem but I can't figure out where it's happening.

**Comment by jeremy-keenan** [comment]
OK, figured it out. I had to copy the files of the library folder to be in the same directory as the Max.exe file - not in a folder of their own.

The external now works!

**Comment by RVirmoors** [comment]
> OK, I was able to fix the above problem and build successfully.
> 
> There was an errant invisible character in the main .cpp file - deleting it worked.

oh wow, i think this solves [this issue](https://github.com/acids-ircam/nn_tilde/issues/37) for which i had filed [this PR](https://github.com/acids-ircam/nn_tilde/pull/36/files)

the main repo should really be updated, otherwise every Windows user will keep running into this problem.

**Comment by jeremy-keenan** [comment]
> oh wow, i think this solves [this issue](https://github.com/acids-ircam/nn_tilde/issues/37) for which i had filed [this PR](https://github.com/acids-ircam/nn_tilde/pull/36/files)
> 
> the main repo should really be updated, otherwise every Windows user will keep running into this problem.

Ah, yes that's the same error. Fixed by a single backspace, but it confused me for quite a while!

**Comment by caillonantoine** [comment]
the repo has been updated in #3f6a8ab6d5ee43ba5a2b079db478ac8ee2336072 :)
