### ISSUE TITLE
About the install issue 

### ISSUE THREAD

**Issue by Abbienew** [acids-ircam/nn_tilde#47]
Hello 
I wonder if anyone here has successfully installed 
nn_tilde with the Mac intel core.  I have faced lots of errors in this command

`cmake ../src/ -DCMAKE_PREFIX_PATH=/path/to/libtorch -DCMAKE_BUILD_TYPE=Release`

, and cannot create any .mxo files. The main issue is below

```
CMake Error at ../cmake/mkl/MKLConfig.cmake:716 (add_library):
add_library cannot create imported target "MKL::MKL" because another target
with the same name already exists.
Call Stack (most recent call first):
../libtorch/share/cmake/Caffe2/public/mkl.cmake:1 (find_package)
../libtorch/share/cmake/Caffe2/Caffe2Config.cmake:103 (include)
../libtorch/share/cmake/libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
frontend/maxmsp/mcs.nn_tilde/CMakeLists.txt:18 (find_package)
```

And sometimes the existing libs likeTorchConfig.cmake and related files cannot be found for the command.

Meanwhile, I tried to copy past the mxo files from Pre-built binaries to the nn_tilde code package and create an external folder. The nn~ works but other functions don't work.

Photo as [[ https://cycling74.com/forums/about-the-issue-install-nn_tilde](https://cycling74.com/forums/about-the-issue-install-nn_tilde)] 

Looking for any solutions to work the function perfectly! and hope to have an easier way to install it in the near future.

Thank you :)

**Comment by caillonantoine** [comment]
Do you have the wheel.ts model ?
