### ISSUE TITLE
Extremely slow inference nn~ on Raspberry Pi 4 / Jetson Nano Dev kit

### ISSUE THREAD

**Issue by moiseshorta** [acids-ircam/nn_tilde#5]
Hi,

I have successfully built and ran nn~ for Pure Data on both Raspberry Pi 4 and a Jetson Nano Dev Kit.

Unfortunately, even though I've tried a very lean RAVE model, `capacity = 5`, when generating I'm still experiencing severe buffer dropouts in the audio.

Are there any tips in order to have a smooth signal from he nn~ in a resource limited device such as the Raspi4?

Just to note, I'm running on a Raspi 4 8GB.

Thanks!

**Comment by caillonantoine** [comment]
Hi! What method are you using ? Prior generation or reconstruction ? Either way, increasing the buffer size should speed up things !

**Comment by caillonantoine** [comment]
the prior should be downgraded as well ! try with a buffer size of 16384 and using only reconstructions !

**Comment by caillonantoine** [comment]
And yes, the stereo flag adds up to the computational load !

**Comment by moiseshorta** [comment]
Thank you, I will see if this fixes things so it can become usable in a live performance context!

**Comment by moiseshorta** [comment]
Here is an example of how it is sounding like. Here I am using only the encode/decode functions.

I am using ALSA as the audio driver and have an external soundcard connected with USB3:

https://drive.google.com/file/d/1eo7kLrlzl-QNXCQDKMaP2xtWIrqD7k7a/view?usp=drivesdk

**Comment by CarloCattano** [comment]
I have a similar situation with custom models and with the example wheel.ts as well. Even with the suggested buffer of 16384 with 2 nn~ objects for encode & decode .
The 4 cores of the Raspberry Pi 4 at 100% percent

**Comment by moiseshorta** [comment]
Some updates: I've got it to run quite smoothly and without so much latency by training a RAVE model with a '--capacity=4' so far so good! 

This is without a Prior, just using the Encode/Decode functions.
