### ISSUE TITLE
built nn in macminiM1 uses 600% CPU

### ISSUE THREAD

**Issue by rubenxito** [acids-ircam/nn_tilde#50]
Hello! thanks in advance for all the work!!
I've been using the latest arm osx max externals smoothly in a macminiM1 osx 12.6 (50-150% CPU)
but wanted to test if I could build myself the max externals...
I´m using the last repo in pycharm
after some difficulties (avoiding an error writing a tag for the repo and downloading libtorch from here –https://github.com/mlverse/libtorch-mac-m1/releases) it seems like i've built the externals with no errors in console, but...
The 3 externals are 443,7 MB, way bigger than the originals
and when I try to use them in m4L in ableton, it doesn't work because max consumes 600% CPU...
best

**Comment by caillonantoine** [comment]
Have you tried using the official libtorch builds for macos arm64 ? ([link](https://anaconda.org/pytorch/pytorch/2.0.0/download/osx-arm64/pytorch-2.0.0-py3.10_0.tar.bz2))

**Comment by rubenxito** [comment]
Hi! sorry for the delay, I've just tried to build with the libtorch you linked, but i'm afraid it does not resolve the problem, when I use the externals CPU still goes to 600%, may be i'm missing something...
Here's the terminal process (from pycharm) just in case:
thanks!

CMAKE_OSX_ARCHITECTURES: arm64
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.21.12.0
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.21.12.0
v2.1.17
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.21.12.0
v2.1.17
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.21.12.0
v2.1.17
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/user/PycharmProjects/RAVE_nn_tilde/build
(venv-rave_nn) user@user-M1 build % make
[ 33%] Built target backend
[ 44%] Linking CXX CFBundle shared module "/Users/user/PycharmProjects/RAVE_nn_tilde/src/externals/nn~.mxo/Contents/MacOS/nn~"
ld: warning: dylib (/opt/homebrew/lib/libprotobuf.3.21.12.0.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: ld: warning: dylib (/opt/homebrew/lib/libc10.dylib) was built for newer macOS version (12.0) than being linked (11.0)
dylib (/opt/homebrew/lib/libtorch_cpu.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: dylib (/opt/homebrew/lib/libtorch.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: dylib (/opt/homebrew/lib/libc10.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(AbstractConfig.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(CuptiActivityProfiler.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ActivityProfilerController.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ActivityProfilerProxy.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ActivityType.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(Config.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ConfigLoader.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(CuptiActivityApi.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(DaemonConfigLoader.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(Demangle.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(GenericTraceActivity.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ILoggerObserver.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(IpcFabricConfigClient.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(Logger.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(init.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(output_csv.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(output_json.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ThreadUtil.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(libkineto_api.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
Copy PkgInfo
Copy Torch Libraries
Codesign external
/Users/user/PycharmProjects/RAVE_nn_tilde/src/frontend/maxmsp/nn_tilde/../../../externals/nn~.mxo: replacing existing signature
[ 55%] Built target nn_tilde
[ 66%] Linking CXX CFBundle shared module "/Users/user/PycharmProjects/RAVE_nn_tilde/src/externals/mc.nn~.mxo/Contents/MacOS/mc.nn~"
ld: warning: dylib (/opt/homebrew/lib/libtorch.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: dylib (/opt/homebrew/lib/libprotobuf.3.21.12.0.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: dylib (/opt/homebrew/lib/libc10.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: dylib (/opt/homebrew/lib/libc10.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(AbstractConfig.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(CuptiActivityProfiler.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ActivityProfilerController.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ActivityProfilerProxy.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: dylib (/opt/homebrew/lib/libtorch_cpu.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ActivityType.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(Config.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ConfigLoader.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(CuptiActivityApi.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(DaemonConfigLoader.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(Demangle.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(GenericTraceActivity.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ILoggerObserver.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(IpcFabricConfigClient.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(Logger.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(init.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(output_csv.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(output_json.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ThreadUtil.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(libkineto_api.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
Copy PkgInfo
Copy Torch Libraries
Codesign external
/Users/user/PycharmProjects/RAVE_nn_tilde/src/frontend/maxmsp/mc.nn_tilde/../../../externals/mc.nn~.mxo: replacing existing signature
[ 77%] Built target mc.nn_tilde
[ 88%] Linking CXX CFBundle shared module "/Users/user/PycharmProjects/RAVE_nn_tilde/src/externals/mcs.nn~.mxo/Contents/MacOS/mcs.nn~"
ld: warning: dylib (/opt/homebrew/lib/libtorch.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: dylib (/opt/homebrew/lib/libc10.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: dylib (/opt/homebrew/lib/libprotobuf.3.21.12.0.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: dylib (/opt/homebrew/lib/libc10.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(AbstractConfig.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(CuptiActivityProfiler.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ActivityProfilerController.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ActivityProfilerProxy.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ActivityType.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: dylib (/opt/homebrew/lib/libtorch_cpu.dylib) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(Config.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ConfigLoader.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(CuptiActivityApi.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(DaemonConfigLoader.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(Demangle.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(GenericTraceActivity.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ILoggerObserver.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(IpcFabricConfigClient.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(Logger.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(init.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(output_csv.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(output_json.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(ThreadUtil.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/opt/homebrew/lib/libkineto.a(libkineto_api.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)
Copy PkgInfo
Copy Torch Libraries
Codesign external
/Users/user/PycharmProjects/RAVE_nn_tilde/src/frontend/maxmsp/mcs.nn_tilde/../../../externals/mcs.nn~.mxo: replacing existing signature
[100%] Built target mcs.nn_tilde

**Comment by caillonantoine** [comment]
It appears your are building `nn~` with libtorch installed from homebrew `/opt/homebrew/lib/`. I'm not sure if the problem is coming from that place, but the repeated message ` was built for newer macOS version (12.0) than being linked (11.0)` might be a hint

**Comment by rubenxito** [comment]
Thanks! I think I solved it, I manually installed the official libtorch builds for macos arm64 for python 3.9, and I've built the externals.
I only get this error:
v1.5.2
CMake Warning at /usr/local/lib/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /usr/local/lib/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  frontend/maxmsp/mc.nn_tilde/CMakeLists.txt:18 (find_package)

but the mxo seem to work fine (no CPU overload :)

best
