### ISSUE TITLE
Audio Output on Enable , but no incoming audio 

### ISSUE THREAD

**Issue by CarloCattano** [acids-ircam/nn_tilde#8]
![image](https://user-images.githubusercontent.com/17380530/167469982-857467d3-5ba8-41fe-82a1-c872bcbb2bba.png)

The object outputs audio when enabled even though there is no audio input feeding it.
Happens with all models tried 

	- "Max version" : "Version 8.1.10 (f1acba9) (64-bit windows)",
	
	- "OSversion" : "Microsoft Windows 10  (build 19041), 64-bit",

**Comment by caillonantoine** [comment]
Hi, what kind of sound is being outputted ?

**Comment by CarloCattano** [comment]
Understood. It happened with the wheel dataset too and heard this voice whispering out of the blue and got spooked. All good, if it's a feature we will just patch a gate on it
